# -*- coding: utf-8 -*-
"""day_6_python_for_ai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ybj4_I0dzs4mkpLUOUHqApUHh2c5gLo5
"""

import pandas as pd
scores = pd.Series([90,85,67], index=['amir', 'sara', 'noha'])
print(scores)

data = {
    "name": ["Amir", "Sara", "Leo"],
    "quiz1": [90, 70, 82],
    "quiz2": [85, 60, 77],
}
df = pd.DataFrame(data)
print(df)

# fields  or columns
# records or rows

print(df.shape)

print(df.columns)

print(df.dtypes)

df.head(2)

df.describe()

print(df['quiz1'])

print(df['name'])

print(df[['name' , 'quiz1','quiz2']])

df = df.set_index('name')
print(df)



df

print(df.loc['Sara'])

print(df.iloc[1])

df.head()

passed = df[df['quiz1'] >= 80]
print(passed)

df.head()

print(df[df['quiz2'] <=80])

both = df[(df["quiz1"] >= 80) | (df["quiz2"] >= 80)]
print(both)

print(1 and 0)

print(1 or 1)

print(df.sort_values("quiz1"))  # smallest quiz1 first
print(df.sort_values("quiz1", ascending=False))  # largest first

df.head()

df['average'] = (df['quiz1'] + df['quiz2']) / 2
print(df)

df['passed'] = df['average']>= 70
print(df)
print("-----------------")
print(df[["name", "average", "passed"]])

import numpy as np
df.loc[1,'quiz2']= np.nan

df

print(df.isna())

print(df['quiz2'].isna().sum())

filled =df.fillna(65)
print(filled)

import numpy as np
df.loc[1,'quiz2']= np.nan

dropped = df.dropna()
print(dropped)

data = {
"name": ["Amir", "Sara", "Leo", "Nina"],
"group": ["A", "B", "A", "B"],
"score": [90, 70, 82, 60],
}
df = pd.DataFrame(data)
print(df.groupby("group")['score'].mean())

print(df.groupby("group")["score"].count())

print(df.groupby("group")["score"].max())

print(df.groupby("group")["score"].min())

print(df.groupby("group")["score"].agg(["mean", "max", "count"]))

df = pd.DataFrame({"x": [1, 2, 3]})
df["y"] = df["x"] * 10
print(df["y"].tolist())
print(df["y"])

df.head()

