# -*- coding: utf-8 -*-
"""day-5_python_for_ai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DE3ffHxlt8QXSBGuk3XrV9_UE_pjKaeo
"""

from math import sqrt
sqrt(4)

scores = [12,4,8,10]
print(scores*2)

import numpy as np
scores = np.array(scores)
print(scores*2)

arr = np.array([1,2,3,4,5])
print(arr + 2)

np.zeros(5)

np.ones(5)

# np.arange(start , stop, step)
np.arange(0,10,2)

np.arange(0,11,2)

np.linspace(0,1,5)   # (start, stop, count)

np.linspace(0,100,6)

scores = np.array([90,85,78,92,88])
scores.shape

scores.ndim

scores.dtype

arr = np.array([10,20,30]) #1d array  shape = (3,)

arr2 = np.array([
    [90,85,78,92],
    [70,88,95,60],
    [82,89,24,54]
])

arr2.shape

arr2.ndim

arr = np.array([
    [[1,2,3,4],
     [1,2,3,4]],
      [[1,2,3,4],
       [1,2,3,4]],
        [[1,2,3,4],
         [1,2,3,4]]
    ])
arr2 = np.array([
    [90,85,78,92],
    [70,88,95,60],
    [82,89,24,54]
])

arr.shape

"""# indexing and slicing"""

arr = np.array([10,20,30,40])
print(arr[0])

print(arr[-1])

arr2 = np.array([
    [90,85,78,92],
    [70,88,95,60],
    [82,89,24,54]
])

print(arr2[1][1])

print(arr2[2][3])

arr2 = np.array([
    [[1,2],[3,4],[5,6]],
    [[7,8],[9,10],[11,12]],
    [[13,14],[15,16],[17,18]]
])

print(arr2[2][1][1])
print(arr2[1][2][1])

arr = np.array([10,20,30,40])
print(arr[1:3])

arr2 = np.array([
    [90,85,78,92],
    [70,88,95,60],
    [82,89,24,54]
])

print(arr2[0:2,1:3])

arr2[1,1:3]

arr2[:,1]

arr2[:, :]

"""# boolean indexing"""

scores= np.array([55,90,43,81,89])
passed = scores[scores>=60]
print(passed)

[scores>=60]

ages[ages>30]

"""# array math"""

a = np.array([1,2,3])
b = np.array([10,20,30])
a + b

a*b

a +5

grades = np.array([
    [90,85,76,67],
    [70,88,77,90]
])

bonus =np.array([2,2,0,4])

grades+bonus

# scores = [1,2,3,4]
# for s in scores:
#   s+=3
#   print(s)

scores= np.array([55,90,43,81,89])
print(scores.sum())

print(scores.mean())

print(scores.max())
print(scores.min())

print(scores.std())

grades = np.array([
    [90,85,76,67],
    [70,88,77,90]
])

print(grades.sum())
print(grades.sum(axis=1))
print(grades.sum(axis=0))

grades = np.array([
    [90,85,76,67],
    [70,88,77,90]
])
print(grades.mean())
print(grades.mean(axis=1))
print(grades.mean(axis=0))

"""# reshape"""

nums = np.arange(1,13)

print(nums)

grid = nums.reshape(3,4)

print(grid)

grid = nums.reshape(2,6)
grid

grid = nums.reshape(3,3)
grid

"""# random"""

np.random.seed(23)
dice = np.random.randint(1,7,size =5)
print(dice)

"""# **sorting**"""

scores= np.array([55,90,43,81,89])
np.sort(scores)

print(scores.argmax())

