# -*- coding: utf-8 -*-
"""python_for_ai_day2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l3qnnVpHHErlIuWwK8xWQ5RT4hlErFud

# Conditions
"""

x = 3
if (x==2):
  print('two')
elif (x == 3):
  print('three')
else:
  print('others')

#  A simple model-confidence gate
confidence = 0.4

if confidence >= 0.9:
    label = "high confidence"
elif confidence >= 0.6:
    label = "medium confidence"
else:
    label = "low confidence — flag for review"

print(label)  # medium confidence

# Nested conditions: checking two things at once
age = 16
has_license = True
if age >= 18:
    if has_license:
        print("Can drive")
    else:
        print("Needs a license")
else:
    print("Too young")

"""# Loops — for"""

languages = ['JavaScript', 'Python', 'Java']
# for(int i = 0 ; i <= len(languages); i++){
#     print(languages[i])
# }

for language in languages:
  print(language)

metrics = {'accuracy': 0.91, 'precision': 0.88, 'recall': 0.85}
for n, v in metrics.items():
    print(f"{n},{v}")

name = 'fatma'
age = 24
department = 'cs'

print(f"name is: {name} , age is: {age} , department is: {department}")

"""# Loops — while"""

dayCount = 0
while dayCount < 6:
    print('We are learning Python')
    dayCount += 1

epoch = 0
loss = 1.0
while epoch < 5 and loss > 0.1:
    loss = loss * 0.6   # pretend the model is improving
    epoch += 1
    print(f"epoch {epoch}: loss={loss:.3f}")

"""# Loops — break Statement"""

i = 1
while i < 6:
    if i == 3:
        break
    print(i) # 1  2
    i += 1

"""# Loops — continue Statement"""

i = 1
while i < 6:
    if i == 3:
        continue
    print(i) # 1  2
    i += 1

i = 0
while i < 6:
    i += 1
    if i == 3:
        continue
    print(i) # 1  2  4  5  6

"""# Python Levels - procedural level"""

def measureTemp(temp):
  if temp < 37:
    return "Too Cold"
  elif temp > 37:
    return "Too Hot"
  return "Normal"
measureTemp(37)
# "Normal"

# A function with no return value (returns None implicitly)
def log_message(msg):
    print(f"[LOG] {msg}")

log_message("Model loaded")   # [LOG] Model loaded

# A function that returns multiple values (as a tuple)
def min_max(values):
    return min(values), max(values)

print(min_max([3, 7, 1, 9, 4]))

l, h = min_max([3, 7, 1, 9, 4])
print(l, h)  # 1 9

"""# Functions — Default Arguments"""

def doSum(x, y=2, z=3):
    total = x + y + z
    print(total)

doSum(2)         # output: 7
doSum(2, 4)      # output: 9
doSum(2, 4, 10)  # output: 16

def doSum(x=4, y=2, z=3):
    total = x + y + z
    print(total)

doSum()         # output: 9
doSum(2, 4)      # output: 9
doSum(2, 4, 10)  # output: 16

# Default arguments are common for optional hyperparameters:
def train(model_name, epochs=10, learning_rate=0.001):
    print(f"Training {model_name} for {epochs} epochs at lr={learning_rate}")

train("QuantumStride")                      # uses both defaults
train("QuantumStride", epochs=25)           # overrides just one

"""# Functions — *args"""

def doSum(*args):
    total = 0
    for i in args:
        total += i
    print(total)

doSum(2, 6)          # output: 8
doSum(2, 4, 5, 15)   # output: 26
doSum(10, 20, 30, 40, 50, 60, 70, 80, 90, 100)  # output: 150

# Handy for functions that average an unknown number of scores:
def average(*scores):
    return sum(scores) / len(scores)

print(average(0.8, 0.9, 0.75, 0.9, 0.7, 0.898))  # 0.8166...

def data(*args):
    for i in args:
        print(i)

data('lara', 'cs', 19, 3.5)

"""# Functions — **kwargs"""

def doSum(**kwargs):
    print(kwargs)
    for k, v in kwargs.items():
        print(k, v)

doSum(x = 2, y = 26, z = 9)
# 2
# 26

# Building a config dict from named arguments — very common in ML code:
def build_config(**kwargs):
    return kwargs

cfg = build_config(batch_size=32, learning_rate=0.001, epochs=10)
print(cfg)  # {'batch_size': 32, 'learning_rate': 0.001, 'epochs': 10}

def doSum(**kwargs):
    total = 0
    for k in kwargs:
        total += kwargs[k]
    print(total)

doSum(x=2, y=26, z= 8)

name = input("enter your name: ")
print(f'hello {name}')

# Reading a number safely (input() always returns a string!)
age_text = input("Enter your age: ")
print(f"In 5 years you'll be {age_text + 5}")

# Reading a number safely (input() always returns a string!)
age_text = input("Enter your age: ")
age = int(age_text)
print(f"In 5 years you'll be {age + 5}")

"""# Commonly Used Functions - Input, Range"""

age_text = int(input("Enter your age: "))
print(f"In 5 years you'll be {age + 5}")

# range(start, stop, step)
range(5)  # [0, 1, 2, 3, 4]
range(1, 6)  # [1, 2, 3, 4, 5]
range(1, 10, 2)  # [1, 3, 5, 7, 9]

for i in range(10):
  print(i)

for i in range(2, 11, 2):
  print(i)

dataset_size = 5
for idx in range(dataset_size):
    print(f"Loading sample {idx+1}")

"""# The One-Line if (Ternary Expression)"""

canFly = False
bird = 'Dove' if canFly else 'penguin'

bird

x = 10
limit = 'high' if x > 5 else 'low'
print(limit)

"""# split() and join()"""

":".join(["1", "Ali", "grp"])

" ".join("ITI") # ['I', 'T' , 'I']

" ".join(['I', 'T' , 'I'])

"Sara Mohamed".split(" ")

"Sara Mohamed".split("")

"Sara Mohamed".split()

"Sara,Mohamed,Ahmed".split(",")

"django:flask".split(":")

"""# Swapping variables"""

x = 4
y = 5
print(x)
print(y)
temp = x
x = y
y = temp
print(x)
print(y)

x, y = 4,5
x , y =  y , x

print(x,y)
print(x, end = ', ')
print(y)

"""# enumerate()"""

languages = ["JavaScript", "Python", "Java"]
for i, l in enumerate(languages):
    print("Element Value: ", l, end=", ")
    print("Element Index: ", i)

"""# is vs =="""

True == 1

True is 1

list1 = [1, 2, 3]
list2 = [1, 2, 3]
print(list1==list2)
print(list1 is list2)
print(id(list1))
print(id(list2))

list1 = [1,2,3]
list2 = list1
print(list1==list2)
print(list1 is list2)
print(id(list1))
print(id(list2))

"""# all() and any()"""

L  = [0, 5, 9, 7, 8]
all(L)   # False  (0 is falsy)

any(L)   # True   (at least one truthy value)

"""# List Methods"""

myList = ["C", "JavaScript", "Python", "Java", "php"]

myList.pop()
myList

myList.pop(1)

myList

myList.append('go')

myList

myList.insert(1, 'javascript')

myList

myList.remove('go')
myList

yourlist = ['cs', 'it', 'is', 'ds']
# myList.extend(yourlist)
# myList

myList += yourlist
myList

"""# Dictionary Methods"""

infoDict = {'track': 'OS', 'name': 'Ahmed', 'age': 17}

infoDict.keys()      # dict_keys(['track', 'name', 'age'])

'name' in infoDict   # True  -> checks the KEYS, not the values

infoDict.items()

addInfoDict = {'track': 'SD', 'branch': 'Zag'}
infoDict.update(addInfoDict)
infoDict

"""# Python Scope"""

name = "Ahmed"
def outerFn():
  name = "Ali"
  def innerFn():
    print(name)
  innerFn()
outerFn()
print(name)

name = "Ahmed"
def outerFn():
  global name
  name = "Ali"
  def innerFn():
    print(name)
  innerFn()

outerFn()
print(name)

name = "Ahmed"
def outerFn():
  global name
  name = "Ali"
  def innerFn():
    print(name)
  innerFn()

outerFn()
print(name)

def outer_fun(a, b):
    def inner_fun(c, d):
        return c + d
    return inner_fun(a, b)

res = outer_fun(5, 10)
print(res)

def outer_fun(a, b):
    def inner_fun(a, b):
        return a + b
    return inner_fun(a, b)

res = outer_fun(5, 10)
print(res)

def fun1(name, age):
  print(name, age)

fun1("Emma", 23)  #postional arguments

fun1(name = "Emma", age = 23)  #keyword arguments

fun1(age = 23, name = "Emma")

fun1("Emma", age=23)  # name = Emma , age = 23

fun1(age=23, name="Emma")

def fun1(name, age):
    print(name, age)
# fun1(name="Emma", 23)

# fun1(age=23, "Emma")

def display_person(*args):
    for i in args:
        print(i)

display_person("Emma","25")

def outer_fun(a, b):
    def inner_fun(c, d):
        return c + d
    return inner_fun(a, b)
    return a

result = outer_fun(5, 10)
print(result)

def fun1(num):
    return num+25

fun1(5)
print(num)

