# -*- coding: utf-8 -*-
"""python_for_ai_day4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19mAQaDkuz8pa4GyH2DPk1l4p-c2OOwff
"""

# employee_1_name = 'ahmed'
# employee_1_age = 30
# employee_1_salary = 4000

# employee_2_name = 'ali'
# employee_2_age = 25
# employee_2_salary = 3500

# employee_3_name = 'mohamed'
# employee_3_age = 35
# employee_3_salary = 5000

"""# oop"""

class Human:
  faults = 10  # class attribute
  # constructor method
  def __init__(self,name,age):
    self.name = name
    self.age = age
    # self.faults = faults
    print('hello from constructor method')

h1 = Human('ahmed',30)  # created an object

h1.name , h1.age

h2 = Human('ali',25)

h2.name, h2.age

h1.faults, h2.faults, Human.faults

Human.name

Human.faults = 10
h1.faults, h2.faults, Human.faults

h1.faults = 5
h1.faults , h2.faults, Human.faults

h3 = Human('mohamed',35)
h3.faults

h1.faults

Human.faults += 2
h1.faults, h2.faults, h3.faults, Human.faults

Human.faults = 5
h1.faults, h2.faults, h3.faults, Human.faults

Human.faults+=5
h1.faults, h2.faults, h3.faults, Human.faults

"""# instance method and class method"""

class Human:
  faults = 0  # class attribute
  # constructor method
  def __init__(self,name,age):
    self.name = name
    self.age = age
    # self.faults = faults
    print('hello from constructor method')
  #instance method
  def speak(self):
    print(f'hello, i am {self.name}')

  @classmethod
  def makefaults(cl):
    cl.faults += 1
    print(cl.faults)

  @staticmethod
  def measureTemp(temp):
    if (temp == 37):
      return 'Normal'
    else:
      return 'not normal'

h1 = Human('ahmed',30)
h1.speak()

# Human.speak()  # error
# Human.speak(h1) # correct

h2 = Human('ali', 25)
h2.speak()

Human.faults, h1.faults

Human.makefaults()

Human.faults, h1.faults

h1.makefaults()
Human.faults, h1.faults

h1.faults = 1

Human.faults, h1.faults

Human.makefaults()
Human.faults, h1.faults

h1.makefaults()
Human.faults, h1.faults

h3 = Human('mohamed',35)

h3.name , h3.age

h3.name = 'lara'

h3.name , h3.age

Human.measureTemp(39)

class Human:
  faults = 0  # class attribute
  # constructor method
  def __init__(self,name,age):
    self.name = name
    self.age = age
    # self.faults = faults
    print('hello from constructor method')
  #instance method
  def speak(self):
    print(f'hello, i am {self.name}')

  @classmethod
  def makefaults(cl):
    cl.faults += 1

class Employee(Human):
  def __init__(self,name,age,salary):
    # Human.__init__(self,name,age)
    super().__init__(name,age)
    self.salary = salary

  def work(self):
    print(f'{self.name} is working')

h = Human('mohamed', 20)
e = Employee('khaled', 30, 4000)

e.speak()

h.salary

e.makefaults()

e.faults

e.work()

h.work()

class Human:
  faults = 0  # class attribute
  # constructor method
  def __init__(self,name,age):
    self.name = name
    self.age = age
    # self.faults = faults
    print('hello from constructor method')
  #instance method
  def speak(self):
    print(f'hello, i am {self.name} and i am human')

  @classmethod
  def makefaults(cl):
    cl.faults += 1

class Employee(Human):
  def __init__(self,name,age,salary):
    # Human.__init__(self,name,age)
    super().__init__(name,age)
    self.salary = salary

  def speak(self):
    super().speak()
    print(f'hello, i am {self.name} and i am employee')


  def work(self):
    print(f'{self.name} is working')

class Teacher(Employee):
  def __init__(self,name,age,salary,subject):
    super().__init__(name,age,salary)
    self.subject = subject
  def speak(self):
    super().speak()
    print(f'i am {self.name}, and i am a teacher')

h = Human('mohamed', 20)
e = Employee('khaled', 30, 4000)
t = Teacher('ali', 40, 5000, 'math')

h.name , e.name, t.name

e.speak(), t.speak()

t.speak()

"""# Multiple inheritance"""

class WingedAnimal:
  def __init__(self):
    self.canFly = True
    print('winged constructor called')
  def get_info(self):
    print(f'can fly: {self.canFly}')

class Mammel:
  def __init__(self):
    self.canBirth = True
    print('mammel constructor called')
  def get_info(self):
    print(f'can birth: {self.canBirth}')

class Bat(WingedAnimal,Mammel):
  def __init__(self):
    # super().__init__()
    Mammel.__init__(self)
    WingedAnimal.__init__(self)
    # print('bat constructor called')

  def get_info(self):
    # super().get_info()
    print('bat info is called')
    # Mammel.get_info(self)
    # WingedAnimal.get_info(self

b = Bat()

b.get_info()

"""# *polymorphism*"""

#  overriding
class WingedAnimal:
  def __init__(self):
    self.canFly = True
    print('winged constructor called')
  def get_info(self):
    print(f'can fly: {self.canFly}')

class Mammel:
  def __init__(self):
    self.canBirth = True
    print('mammel constructor called')
  def get_info(self):
    print(f'can birth: {self.canBirth}')

class Bat(WingedAnimal,Mammel):
  def __init__(self):
    # super().__init__()
    Mammel.__init__(self)
    WingedAnimal.__init__(self)
    # print('bat constructor called')

  def get_info(self):
    # super().get_info()
    print('bat info is called')
    # Mammel.get_info(self)
    # WingedAnimal.get_info(self

#overloading
def summ(*data):
  pass

summ(1,2)
summ(1,2,3,4)
summ(6,7,8,8,9,10)

def summ(a,b):
  print(a+b)

summ(3,4)

summ('a', 'b')

def summ(a:int,b:int):
  print(a+b)

summ(4,5)

summ('a','b')

def summ(x,y):
  return x+y

summ(3,4)

def summ(x,y,z):
  return x+y+z
summ(4,5,6)

"""# Encapsulation"""

class Human:
  faults = 0
  def __init__(self,name,age):
    self.name = name
    self.age = age

h1 = Human('lara', 10)

h1.name  # correct using getter

h1.age= -10  # correct using setter
h1.age

class Human:
  faults = 0
  def __init__(self,name,age):
    self.__name = name
    self.__age = age

  def talk(self):
    print(f'hello, i am {self.__name}')

  @property
  def get_name(self):
    return self.__name
  @property
  def get_age(self):
    return self.__age

  @get_age.setter
  def set_age(self,age):
    if age < 0:
      print('invalid age')
      raise ValueError('invalid age')
    else:
      self.__age = age

h1 = Human('lara', 10)
h1.get_name

h1.age = -20
h1.age

h1.set_age = -10

h1.get_age

h1.get_name()

h1.talk()

