# -*- coding: utf-8 -*-
"""python_day1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Df2lNS2kwbGqus7gy9ZAmKE2EE_zR2ns

# **python is interpreted**
"""

x = 10
print(x)
x = x + 5
print(x)

"""# **indentation**"""

import time  # statement 1

def count(limit):  # statement 2
    result = 0  # statement 3
    for a in range(1, limit + 1):  # statement 4
        for b in range(a + 1, limit + 1):
            for c in range(b + 1, limit + 1):
                if c * c > a * a + b * b:
                    break
                if c * c == (a * a + b * b):
                    result += 1
    return result

"""# **comments**"""

'''
a way to declare a
string paragraph — often used as a
multi-line comment or a docstring
'''

def train_model():
    """This triple-quoted string right after a function
    definition is called a docstring — it documents
    what the function does."""
    pass

# this is a single line comment

x = 5.16
print(int(x))     # 5      -> truncates the decimal
print(float(x))   # 5.16   -> already a float
print(str(x))     # "5.16" -> useful for building log messages

# More conversions you'll use constantly in data pipelines:
print(int("42"))        # 42
print(float("3.14"))    # 3.14
print(bool(0))           # False

print(bool(4))

print(bool('fatma'))

"""# **Operators**"""

x = 6
y = 7
print(x+y)
print(x-y)

print(x*y)

x = 12
y = 3

x /y

x = 14
y = 5
x/y

x // y

x % y

x = 2
y = 3
x ** y

x, y = 17, 5
print(x + y)   # 22
print(x % y)   # 2   -> remainder, useful for FizzBuzz-style checks
print(x ** 2)  # 289 -> squaring, common in loss functions (MSE)
print(x // y)  # 3   -> integer division, useful for batch-count math

x, y, z = 4, 'sara', True
print(x)
print(y)
print(z)
print(x,y,z)

"""# **Assignment Operators **"""

x = 5
x += 3
x

x -= 6
x

x = 2

x *= 7
x

x /= 5

x

x = 14
x //= 3
x

x = 14
x %=3
x

x = 5
x **= 3
x

total_loss = 0
for batch_loss in [0.42, 0.31, 0.28]:
    total_loss += batch_loss   # accumulating loss across batches

print(round(total_loss, 1))  # 1.01

"""# **Comparison Operators **"""

x = 6
y = 4
x ==y

x > y

x != y

"""# **Logic Gates **"""

# and -> AND Logic Gate
# or  -> OR Logic Gate
# not -> NOT Logic Gate

print(True and False)          # False
print(True or False)           # True
print(not False)               # True

print(not (True == 2))         # True

print((False == 0) and (True == 1))  # True

# A realistic AI-flavored check:
confidence = 0.87
is_flagged = False
should_alert = (confidence > 0.8) and (not is_flagged)
print(should_alert)  # True

s = "this is a string"
s = 'this is a string too'

# Strings support handy operations you'll use in text preprocessing:
name = "gpt"
print(name.upper())        # "GPT"

name = 'FATMA MAHMOUD'
print(name.lower())

name = 'fatma mahmoud'
print(name.capitalize())   # "Fatma Mahmoud"

print(len(name))

print(name + " elraey")

print(name * 3)

print('mah' in name)

print('zad' in name)

"""# **Data Structures — List **"""

data = ['lara' , 27, False]
print(data)

print(data[0])
print(data[1])
print(data[2])

print(data[3])

data = ['lara', 13, 'cs', 3.5, ['python', 'js', 'cpp']]
data

data[2:4]

data[3:5]

data[4][1]

data[-1]

data

data.append(0.90)
data

data[1]= 23
data

my_tuple = (1, 'hi', True)
print(my_tuple)
print(my_tuple[1])

my_tuple[0] = 4

my_tuple.append(0.9)
my_tuple

image_shape = (224, 224, 3)   # height, width, channels
print(image_shape[0])  # 224

"""# Data Structures — Dictionaries"""

model = {'name': 'GPT', 'task': 'NLP'}
print(model['name'])
# 'GPT'

model['name'] = 'BERT'
# {'name': 'BERT', 'task': 'NLP'}
model

config = {
'learning_rate': 0.001,
'batch_size': 32,
'epochs': 10,
}

x,  y= 5, 6

for key, value in config.items():
  print(key, "->", value)

for value in config.values():
  print(value)

"""# set"""

names = {'lara', 'sara', 'yara', 'lara'}
print(names)

numbers = {1,2,3,1}
print(numbers)

numbers2 = {3,2,1}
numbers2 - numbers

